port: 5000
auth_service:
 host: "http://localhost:5001"
database:
 driver: "mysql"
 host: "localhost"
 port: "3306"
 user: "root"
 password: ""
 db_name: "dts_microservice"
 config: "charset=utf8&parseTime=True&loc=Local"
